### ISSUE TITLE
运行QQ的时候，可以打开，在点击登录按钮 进入登录界面直接挂了， QQ权限加了的，错误信息如下

### ISSUE THREAD

**Issue by tianqiujie** [DroidPluginTeam/DroidPlugin#105]
这是打开QQ的时候出现的错误：
12-18 10:24:10.603: W/ResourceType(4059): No package identifier when getting value for resource number 0x00000000
12-18 10:24:10.603: W/PackageManager(4059): Failure retrieving resources for com.tencent.mobileqq: Resource ID #0x0
12-18 10:24:10.783: W/System.err(4059): java.io.FileNotFoundException: /data/data/com.example.TestPlugin/Plugin/com.tencent.mobileqq/data/com.tencent.mobileqq/files/Properties: open failed: ENOENT (No such file or directory)
12-18 10:24:10.783: W/System.err(4059):     at libcore.io.IoBridge.open(IoBridge.java:456)
12-18 10:24:10.783: W/System.err(4059):     at java.io.FileInputStream.<init>(FileInputStream.java:76)
12-18 10:24:10.783: W/System.err(4059):     at android.app.ContextImpl.openFileInput(ContextImpl.java:1398)
12-18 10:24:10.783: W/System.err(4059):     at android.content.ContextWrapper.openFileInput(ContextWrapper.java:191)
12-18 10:24:10.783: W/System.err(4059):     at mqq.app.MobileQQ.loadProperites(MobileQQ.java:213)
12-18 10:24:10.783: W/System.err(4059):     at mqq.app.MobileQQ.doInit(MobileQQ.java:154)
12-18 10:24:10.783: W/System.err(4059):     at com.tencent.mobileqq.startup.step.NewRuntime.a(ProGuard:14)
12-18 10:24:10.783: W/System.err(4059):     at com.tencent.mobileqq.startup.step.Step.c(ProGuard:107)
12-18 10:24:10.783: W/System.err(4059):     at com.tencent.mobileqq.startup.step.Step.a(ProGuard:133)
12-18 10:24:10.783: W/System.err(4059):     at com.tencent.mobileqq.startup.step.Step.c(ProGuard:107)
12-18 10:24:10.783: W/System.err(4059):     at com.tencent.mobileqq.startup.director.StartupDirector.a(ProGuard:619)
12-18 10:24:10.783: W/System.err(4059):     at com.tencent.mobileqq.startup.director.StartupDirector.handleMessage(ProGuard:639)
12-18 10:24:10.783: W/System.err(4059):     at android.os.Handler.dispatchMessage(Handler.java:98)
12-18 10:24:10.783: W/System.err(4059):     at android.os.Looper.loop(Looper.java:145)
12-18 10:24:10.793: W/System.err(4059):     at android.os.HandlerThread.run(HandlerThread.java:61)
12-18 10:24:10.793: W/System.err(4059): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
12-18 10:24:10.793: W/System.err(4059):     at libcore.io.Posix.open(Native Method)
12-18 10:24:10.793: W/System.err(4059):     at java.lang.reflect.Method.invoke(Native Method)
12-18 10:24:10.793: W/System.err(4059):     at java.lang.reflect.Method.invoke(Method.java:372)
12-18 10:24:10.793: W/System.err(4059):     at com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:51)
12-18 10:24:10.793: W/System.err(4059):     at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(ProxyHook.java:61)
12-18 10:24:10.793: W/System.err(4059):     at java.lang.reflect.Proxy.invoke(Proxy.java:397)
12-18 10:24:10.793: W/System.err(4059):     at $Proxy15.open(Unknown Source)
12-18 10:24:10.793: W/System.err(4059):     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
12-18 10:24:10.793: W/System.err(4059):     at libcore.io.IoBridge.open(IoBridge.java:442)
12-18 10:24:10.793: W/System.err(4059):     ... 14 more
12-18 10:24:10.853: W/ResourceType(4059): For resource 0x7f0b0330, entry index(816) is beyond type entryCount(816)
12-18 10:24:10.853: W/ResourceType(4059): Failure getting entry for 0x7f0b0330 (t=10 e=816) (error -75)
12-18 10:24:11.173: W/linker(4059): libNativeRQD.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
12-18 10:24:11.173: E/art(4059): No implementation found for java.lang.String com.tencent.feedback.eup.jni.NativeExceptionUpload.registNativeExceptionHandler2(java.lang.String, java.lang.String, int, int) (tried Java_com_tencent_feedback_eup_jni_NativeExceptionUpload_registNativeExceptionHandler2 and Java_com_tencent_feedback_eup_jni_NativeExceptionUpload_registNativeExceptionHandler2__Ljava_lang_String_2Ljava_lang_String_2II)
12-18 10:24:11.203: E/File(4059): fail readDirectory() errno=13
12-18 10:24:11.273: W/ResourceType(4059): For resource 0x7f020349, entry index(841) is beyond type entryCount(90)
12-18 10:24:11.283: W/ResourceType(4059): Failure getting entry for 0x7f020349 (t=1 e=841) (error -75)
12-18 10:24:11.283: E/Resources(4059): RunTimeException
12-18 10:24:11.283: E/Resources(4059): android.content.res.Resources$NotFoundException: Resource ID #0x7f020349
12-18 10:24:11.283: E/Resources(4059):  at android.content.res.Resources.getValue(Resources.java:2452)
12-18 10:24:11.283: E/Resources(4059):  at android.content.res.Resources.startRC(Resources.java:1092)
12-18 10:24:11.283: E/Resources(4059):  at android.app.ActivityThread$mRunnable.run(ActivityThread.java:2955)
12-18 10:24:11.283: E/Resources(4059):  at java.lang.Thread.run(Thread.java:818)
12-18 10:24:11.283: E/MotionRecognitionManager(4059): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@19374be0
12-18 10:24:11.283: E/MotionRecognitionManager(4059): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@24e9be99
12-18 10:24:11.283: E/MotionRecognitionManager(4059): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@24e9be99
12-18 10:24:11.293: E/MagazineCardManager(4059): getService : Could not get the service!
12-18 10:24:11.303: W/ResourceType(4059): No package identifier when getting value for resource number 0x00000000
12-18 10:24:11.303: W/PackageManager(4059): Failure retrieving resources for com.tencent.mobileqq: Resource ID #0x0
12-18 10:24:11.653: E/MotionRecognitionManager(4059): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@208bd8a0
12-18 10:24:11.653: E/MotionRecognitionManager(4059): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@234c2c59
12-18 10:24:11.653: E/MotionRecognitionManager(4059): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@234c2c59
12-18 10:24:11.663: E/MagazineCardManager(4059): getService : Could not get the service!
12-18 10:24:11.663: W/ResourceType(4059): No package identifier when getting value for resource number 0x00000000
12-18 10:24:11.663: W/PackageManager(4059): Failure retrieving resources for com.tencent.mobileqq: Resource ID #0x0
12-18 10:24:24.763: W/System.err(31993): java.net.SocketTimeoutException
12-18 10:24:24.763: W/System.err(31993):    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
12-18 10:24:24.763: W/System.err(31993):    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
12-18 10:24:24.763: W/System.err(31993):    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okio.Okio$2.read(Okio.java:116)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:150)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:97)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:202)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:119)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:798)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:405)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
12-18 10:24:24.763: W/System.err(31993):    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
12-18 10:24:24.763: W/System.err(31993):    at com.tencent.mobileqq.msf.core.a.b.run(ConfigManager.java:1620)

这是点击QQ登录按钮的时候出现的错误：
12-18 10:26:17.263: W/System.err(4059): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.content.Context.getContentResolver()' on a null object reference
12-18 10:26:17.263: W/System.err(4059):     at android.media.AudioManager.querySoundEffectsEnabled(AudioManager.java:3082)
12-18 10:26:17.263: W/System.err(4059):     at android.media.AudioManager.playSoundEffect(AudioManager.java:2991)
12-18 10:26:17.263: W/System.err(4059):     at android.view.ViewRootImpl.playSoundEffect(ViewRootImpl.java:6342)
12-18 10:26:17.263: W/System.err(4059):     at android.view.View.playSoundEffect(View.java:19304)
12-18 10:26:17.263: W/System.err(4059):     at android.view.View.performClick(View.java:5241)
12-18 10:26:17.263: W/System.err(4059):     at android.widget.TextView.performClick(TextView.java:10530)
12-18 10:26:17.263: W/System.err(4059):     at android.view.View$PerformClick.run(View.java:21185)
12-18 10:26:17.263: W/System.err(4059):     at android.os.Handler.handleCallback(Handler.java:739)
12-18 10:26:17.263: W/System.err(4059):     at android.os.Handler.dispatchMessage(Handler.java:95)
12-18 10:26:17.263: W/System.err(4059):     at android.os.Looper.loop(Looper.java:145)
12-18 10:26:17.263: W/System.err(4059):     at android.app.ActivityThread.main(ActivityThread.java:6872)
12-18 10:26:17.263: W/System.err(4059):     at java.lang.reflect.Method.invoke(Native Method)
12-18 10:26:17.263: W/System.err(4059):     at java.lang.reflect.Method.invoke(Method.java:372)
12-18 10:26:17.263: W/System.err(4059):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
12-18 10:26:17.263: W/System.err(4059):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
12-18 10:26:17.323: W/linker(4059): libcodecwrapperV2.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
12-18 10:26:17.893: W/AccessSchedulerStorageManager(4059): cache failed for apn:ssid_"tian_cq"d0:fa:1d:73:43:cf

**Comment by tianqiujie** [comment]
打开微信，停留在splash页面 然后卡死 

12-18 10:36:49.575: E/MagazineCardManager(22150): getService : Could not get the service!
12-18 10:36:49.985: E/ActivityThread(22150): Failed to find provider info for com.tencent.mm.coolassist.debugprovider
12-18 10:36:49.995: W/MicroMsg.xlogger(22150): JNI_Xlog_onCreate
12-18 10:36:50.055: W/jni crash monitor(22150): JNI_OnLoad
12-18 10:36:50.965: E/MotionRecognitionManager(22150): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@9597da9
12-18 10:36:50.965: E/MotionRecognitionManager(22150): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@191a2f2e
12-18 10:36:50.965: E/MotionRecognitionManager(22150): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@191a2f2e
12-18 10:36:50.975: E/MagazineCardManager(22150): getService : Could not get the service!
12-18 10:36:50.975: W/ResourceType(22150): No package identifier when getting value for resource number 0x00000000
12-18 10:36:50.975: W/PackageManager(22150): Failure retrieving resources for com.tencent.mm: Resource ID #0x0

**Comment by F8LEFT** [comment]
楼主我也遇到这个问题了，请问楼主解决了吗？
另外我没有见到你这样的log啊？请问是怎么设置出来的？

**Comment by cmzy** [comment]
重复：https://github.com/Qihoo360/DroidPlugin/issues/110

**Comment by cayden** [comment]
我也遇到这样的问题，不知道目前是否已经解决。

**Comment by jikefeng** [comment]
我是登陆的时候显示，无网络连接，你们有这个问题吗

**Comment by slimboy2008** [comment]
我的可以进登录界面，但是无法连接网络

**Comment by bhui** [comment]
遇到同样的问题，不知道目前是否已经解决?

**Comment by zhengbobo** [comment]
楼主目前这个问题解决了吗！！！

**Comment by tianqiujie** [comment]
早放弃了...

**Comment by zhengbobo** [comment]
好的，我尝试下其它方法。
