### ISSUE TITLE
使用DroidPlugin会导致Toast报NPE

### ISSUE THREAD

**Issue by testcc3** [DroidPluginTeam/DroidPlugin#155]
03-28 17:22:35.877: I/HomeFragment(15008): position:0
03-28 17:22:35.899: W/Toast(15008): From com.test.hulu, go ahead.
03-28 17:22:35.914: D/AndroidRuntime(15008): Shutting down VM
03-28 17:22:35.914: W/dalvikvm(15008): threadid=1: thread exiting with uncaught exception (group=0x41b26ba8)
03-28 17:22:35.936: E/AndroidRuntime(15008): FATAL EXCEPTION: main
03-28 17:22:35.936: E/AndroidRuntime(15008): Process: com.test.hulu, PID: 15008
03-28 17:22:35.936: E/AndroidRuntime(15008): java.lang.NullPointerException
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:540)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at android.widget.Toast$TN.handleShow(Toast.java:402)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at android.widget.Toast$TN$1.run(Toast.java:331)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at android.os.Handler.handleCallback(Handler.java:733)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at android.os.Looper.loop(Looper.java:136)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at android.app.ActivityThread.main(ActivityThread.java:5016)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
03-28 17:22:35.936: E/AndroidRuntime(15008): 	at dalvik.system.NativeStart.main(Native Method)

常规使用Toast：
Toast.makeText(activity, "点击区域A的第" + ( position + 1 ) + "个插件", Toast.LENGTH_SHORT).show();

@cmzy 请问是什么原因？

**Comment by testcc3** [comment]
小米3开发版

**Comment by cmzy** [comment]
这是插件的崩溃还是宿主的？

**Comment by testcc3** [comment]
是宿主应用的

**Comment by cmzy** [comment]
不应该啊，能否提供更多的信息？执行上下文？

**Comment by testcc3** [comment]
Manifest.xml里Application设置的不对，已经ok了，多谢

**Comment by cmzy** [comment]
啥不对？发出来让其它人也看看。。免得再踩坑。
