### ISSUE TITLE
PluginManager.getInstance().isConnected()一直返回false

### ISSUE THREAD

**Issue by testcc3** [DroidPluginTeam/DroidPlugin#156]
显示调用了PluginManager.getInstance().addServiceConnection(this)
以后也还是不行

PluginManager.getInstance().installPackage也一直返回-1

求助，多谢。

**Comment by cmzy** [comment]
请参见FAQ的说明。https://github.com/DroidPluginTeam/DroidPlugin/wiki/FAQ
