### ISSUE TITLE
在插件中调起微信、QQ支付和分享，有什么好的思路

### ISSUE THREAD

**Issue by JackCho** [DroidPluginTeam/DroidPlugin#168]
我目前的想法是这样的，以Host的身份去完成这些操作，如微信支付完毕后回调的host的.wxapi.WxPayEnteryActivity，然后再去调起插件的WxPayEnteryActivity。
这样实现的话，会导致插件APK和宿主APK都要有一套支付账号，如果业务上不可承受的话，还有其他更优的做法么？

**Comment by mdhuang** [comment]
这个问题确实很苦恼，微信SDK对应用进行了校验，插件无法正常地调用微信SDK，关注这个问题的进展

**Comment by asLody** [comment]
近期提交将支持微信和QQ的SDK。

**Comment by mdhuang** [comment]
非常赞。能否先描述一下解决思路，项目中现在遇到了这个问题比较急

**Comment by JackCho** [comment]
同求，看下能否避免上面描述的情况

**Comment by yuhuayi** [comment]
@asLody 请问相关代码已经提交了吗，我测试的时候，发现通过插件有几率性的可以调起微信分享（但是回调WXEntryActivity 从来没成功过）。不清楚具体原因是什么，只是简单测试分享了

**Comment by HugoXX** [comment]
#262 
我只验证了微信分享，支付。
如果用户没有登录，这时候可以唤起分享，支付的。
如果用户登陆了，微信对应用有校验，是不能唤起的。

**Comment by cmzy** [comment]
可以看下这个：https://github.com/DroidPluginTeam/DroidPlugin/issues/262#issuecomment-288647329
