### ISSUE TITLE
集成了腾讯 bugly的app，crash上传功能失效

### ISSUE THREAD

**Issue by SheepYoung** [DroidPluginTeam/DroidPlugin#180]
如题， 如果app集成了腾讯的bugly sdk， 插件（app）crash之后，不能看到日志上传。

**Comment by smile3670** [comment]
我用友盟的没有问题，在宿主程序和插件中都分别集成了友盟sdk，crash日志都能正常手机

**Comment by javalover** [comment]
插件里有个 MyCrashHandler 不要启用这个类
在 PluginHelper#applicationAttachBaseContext 里调用的，可能覆盖了你sdk的 Handler

**Comment by cmzy** [comment]
@javalover 说的对。bug close
