### ISSUE TITLE
不能访问Assets

### ISSUE THREAD

**Issue by r17171709** [DroidPluginTeam/DroidPlugin#184]
我在使用插件过程中，发现webview.loadUrl，远程网页可以访问，但是本地Assets的都不可以，这是什么原因呢

**Comment by cmzy** [comment]
这是Android系统WebView的bug。有一个WebView相关的hook可以解决，但此hook在锤子手机上有bug。

**Comment by zqyu2** [comment]
@cmzy 是这个吗 WebViewFactoryProviderHookHandle？ 好像在7.0上有问题：initApplicationContext方法找不到。 这个有做适配吗？
