### ISSUE TITLE
can not install app 

### ISSUE THREAD

**Issue by luoqii** [DroidPluginTeam/DroidPlugin#187]
05-17 17:31:19.722 16333-18148/com.example.TestPlugin I/IPackageManagerHookHandle: getPackageInfo(com.example.TestPlugin) fail,pkginfo is null
05-17 17:31:21.122 16333-18148/com.example.TestPlugin I/IPluginManagerImpl: Save com.youku.tv.debug signature of 0,md5=2537FDB3DF75FD67C5EC4ECD246BE71A
05-17 17:31:21.582 16333-18148/com.example.TestPlugin D/NativeLibraryHelperCompat: supportedAbis : []
05-17 17:31:23.105 16333-18148/com.example.TestPlugin D/NativeLibraryHelperCompat: supportedAbis : [armeabi-v7a]
05-17 17:48:53.856 16333-18148/com.example.TestPlugin W/PluginManager: /data/app/com.youku.tv.debug-1/base.apk install result -3

**Comment by cmzy** [comment]
插件so不被支持，请看源码。
