### ISSUE TITLE
请问，为什么我拷贝apk放入sd卡  点击安装的时候弹出安装失败，申请的权限太多？

### ISSUE THREAD

**Issue by mcdonaldLiu** [DroidPluginTeam/DroidPlugin#189]
能帮忙解答一下这个问题么，谢谢了

**Comment by jikefeng** [comment]
权限不够呗，host占的坑不够多

**Comment by tiann** [comment]
提issue之前，先搜索是不是有人已经提了是一个好习惯。

https://github.com/DroidPluginTeam/DroidPlugin/issues?utf8=%E2%9C%93&q=%E6%9D%83%E9%99%90%E8%BF%87%E5%A4%9A

**Comment by cmzy** [comment]
CLOSED
