### ISSUE TITLE
Android N not support

### ISSUE THREAD

**Issue by Aloneter** [DroidPluginTeam/DroidPlugin#195]
1. 日志
   03-15 20:49:58.086 E/SELinux (  408): avc:  denied  { find } for service=window pid=10449 uid=10380 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:window_service:s0 tclass=service_manager permissive=0
   03-15 20:49:58.242 E/DatabaseUtils( 8339): Writing exception to parcel
   03-15 20:49:58.242 E/DatabaseUtils( 8339): java.lang.SecurityException: com.feiniu.market was not granted  this permission: android.permission.WRITE_SETTINGS.
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at android.provider.Settings.isCallingPackageAllowedToPerformAppOpsProtectedOperation(Settings.java:9004)
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at android.provider.Settings.checkAndNoteWriteSettingsOperation(Settings.java:8886)
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:905)
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:880)
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:241)
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at android.content.ContentProvider$Transport.call(ContentProvider.java:399)
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
   03-15 20:49:58.242 E/DatabaseUtils( 8339):  at android.os.Binder.execTransact(Binder.java:562)
   03-15 20:49:58.252 D/DeviceId(10449): Settings.System.getString or putString failed
   03-15 20:49:58.255 E/DatabaseUtils( 8339): Writing exception to parcel
   03-15 20:49:58.255 E/DatabaseUtils( 8339): java.lang.SecurityException: com.feiniu.market was not granted  this permission: android.permission.WRITE_SETTINGS.
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at android.provider.Settings.isCallingPackageAllowedToPerformAppOpsProtectedOperation(Settings.java:9004)
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at android.provider.Settings.checkAndNoteWriteSettingsOperation(Settings.java:8886)
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:905)
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:880)
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:241)
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at android.content.ContentProvider$Transport.call(ContentProvider.java:399)
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
   03-15 20:49:58.255 E/DatabaseUtils( 8339):  at android.os.Binder.execTransact(Binder.java:562)
   03-15 20:49:58.255 D/DeviceId(10449): Settings.System.getString or putString failed
2. 分析
   SElinux问题
   对比N版本和M版本SELinux策略区别， 出错原因是如下N版本策略变化:
        (1) untrusted_app程序已经不允许通过ServiceManager.getService访问定义为system_api_service的服务,第三方应用需要放到                 /system/priv-app下才能
          # TODO: remove this once priv-apps are no longer running in untrusted_app
          allow untrusted_app system_api_service:service_manager find;
       (2) window服务目前M和N版本中的定义为system_api_service
           external/sepolicy/service_contexts
           window                                    u:object_r:window_service:s0
           external/sepolicy/service.te
           type window_service, system_api_service, system_server_service, service_manager_type;

**Comment by cmzy** [comment]
不是selinux的问题，我已经支持了，代码还没放出来。

**Comment by lgengsy** [comment]
什么时间能放出来代码呢 ？？ @cmzy

**Comment by cmzy** [comment]
fixed
