### ISSUE TITLE
点击物理back 低概率出现这个错误

### ISSUE THREAD

**Issue by SheepYoung** [DroidPluginTeam/DroidPlugin#196]
java.lang.RuntimeException
Could not read input channel file descriptors from parcel.
android.view.InputChannel.nativeReadFromParcel(Native Method)
android.view.InputChannel.readFromParcel(InputChannel.java:148)
android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
com.android.internal.view.InputBindResult.<init>(InputBindResult.java:62)
com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:102)
com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:99)
com.android.internal.view.IInputMethodManager$Stub$Proxy.windowGainedFocus(IInputMethodManager.java:712)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.morgoo.droidplugin.hook.HookedMethodHandler.doHookInner(HookedMethodHandler.java:51)
com.morgoo.droidplugin.hook.binder.BinderHook.invoke(BinderHook.java:58)
com.morgoo.droidplugin.hook.binder.IInputMethodManagerBinderHook.invoke(IInputMethodManagerBinderHook.java:39)
$Proxy10.windowGainedFocus(Native Method)
android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1169)
android.view.inputmethod.InputMethodManager.onWindowFocus(InputMethodManager.java:1379)
android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3277)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:136)
android.app.ActivityThread.main(ActivityThread.java:5315)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
dalvik.system.NativeStart.main(Native Method)

**Comment by Roger-Zhou** [comment]
你好，想问一下这个问题怎么解决的
