### ISSUE TITLE
微信无法发起群聊，QQ登录提示网络无法连接

### ISSUE THREAD

**Issue by slimboy2008** [DroidPluginTeam/DroidPlugin#205]
DP 运行微信，无法发起群聊是什么问题？ 可以在已有的群里面聊，也可以面对面建群，但不能新发起。

另外，打开QQ 进入登录界面之后会提示网络无法连接？

这2个问题，大家是怎么解决的？

**Comment by gdpancheng** [comment]
我无法安装微信 提示需要的权限太多 无法加载

**Comment by zhengbobo** [comment]
@gdpancheng 是你权限不够的原因
