### ISSUE TITLE
微信发起群聊报这个错

### ISSUE THREAD

**Issue by slimboy2008** [DroidPluginTeam/DroidPlugin#216]
06-13 19:04:42.118 822-840/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.tencent.mm.ui.ACTION_ACTIVE flg=0x10 (has extras) } from com.example.TestPlugin2 (pid=9923, uid=10396) requires com.tencent.mm.permission.MM_MESSAGE due to registered receiver BroadcastFilter{43404ea0 u0 ReceiverList{43404df0 9923 com.example.TestPlugin2:PluginP05/10396/u0 remote:43307d48}}

**Comment by cmzy** [comment]
这个权限问题已经解决了，但是还是无法创建。。没找到原因。

**Comment by cmzy** [comment]
我已经解决了，在本地代码库中。还没提交呢。

**Comment by slimboy2008** [comment]
太好了！期待新版本
