### ISSUE TITLE
插件之间使用Intent和ContentProvider夸进程交互一定会OOM

### ISSUE THREAD

**Issue by cloudsthunder** [DroidPluginTeam/DroidPlugin#225]
插件之间在长时间使用Intent和ContentProvider进行夸进程交互的过程中，软件在运行一段时间后一定会OOM。插件内部并没有一直在创建线程，只是在夸进程交互数据。OOM时DroidPlugin内部一直在创建线程，而且线程不会被回收。

**Comment by fightingyuman** [comment]
Yes, I have met the same issue. Maybe DroidPlugin is not suitable for plenty of  inter-process communiction between plugins or between plugin and host.

**Comment by cmzy** [comment]
这篇报告说楼主是恶意软件作者。[Triada](http://www.freebuf.com/news/131614.html)
