### ISSUE TITLE
报错： abi 、32位、不支持插件

### ISSUE THREAD

**Issue by CaptainJno** [DroidPluginTeam/DroidPlugin#237]
运行TestPlugin项目，在“待安装”界面选择安装我的apk，提示”宿主不支持插件的abi环境，可能宿主运行时为64位，但插件只支持32位“。请问楼主，这是什么原因？

**Comment by CaptainJno** [comment]
作者回我的邮件中解释了原因，以下是原话：
“宿主为32位环境时，插件必须也要支持32位环境。也就是说宿主只有只有32位的so，那么插件也必须要由32位的so或者没有so，如果只有64位的so是不行的。”
又遇到该问题的同学可以参考。

**Comment by jessehev** [comment]
那有没有 宿主为32位时 兼容插件64位的方法？

**Comment by CaptainJno** [comment]
CPU架构应该是不支持的。因为宿主把范围限定得比插件小。好比要往一个小箱子里塞进去一个大箱子，肯定会撑爆的。
以上是个人理解。建议你可以查查CPU架构兼容的资料。
