### ISSUE TITLE
有办法断点调试插件吗？

### ISSUE THREAD

**Issue by xingjiyuan** [DroidPluginTeam/DroidPlugin#238]
难道只能通过log的方式查看插件的运行情况？
想用断点查看插件访问网络接口的url，求方法。

**Comment by zhaizi** [comment]
通过代理 来 查看接口啊  跟APP无关来调试接口

**Comment by xingjiyuan** [comment]
还有其它需求啊，比如查看插件中一个类的初始化的值，这个初始化操作需要与宿主通信完成。

**Comment by cloudsthunder** [comment]
可以试用Attach debugger来调试插件。

**Comment by xingjiyuan** [comment]
断点调试成功，只要有插件的代码就行

**Comment by ouyangzn** [comment]
@xingjiyuan 我想知道怎么调试的，具体操作，求方法
