### ISSUE TITLE
自定义application按照文档说明配置，不混淆的情况可以正常运行，混淆之后启动不了activity

### ISSUE THREAD

**Issue by loverz8023** [DroidPluginTeam/DroidPlugin#240]
android.content.ActivityNotFoundException:Unable to find explicit activity class {对应插件的包名.对应插件的第一个activity},have you declared this activity in your AndroidManifest.xml.

注：
目前的混淆列表增加了两句
-keep class com.morgoo.**{*;}
-dontwarn com.morgoo.droidplugin.**

**Comment by cmzy** [comment]
-keep public class android.util.Singleton
