### ISSUE TITLE
宿主与独立进程中的service通过aidl通信时报TransactionTooLargeException

### ISSUE THREAD

**Issue by xingjiyuan** [DroidPluginTeam/DroidPlugin#242]
自己项目中有一个独立进程的service，集成DroidPlugin之前，一切通信正常。集成之后，通信次数一多就开始报TransactionTooLargeException，无论通信的数据大小是多少都报。注意出现的问题和插件无关。
另外在同一进程中通信就没问题。
求救~
是不是缓存区没及时清空？
有没有什么办法通信时可以选择不通过hook，而正常使用系统原本的通信？

**Comment by triwater** [comment]
楼主是怎么解决的啊
