### ISSUE TITLE
混淆之后，为什么调用不起来service了？

### ISSUE THREAD

**Issue by chonrp27512** [DroidPluginTeam/DroidPlugin#252]
我在混淆前是正常能调用起服务的，可是在混淆后却怎么也调不起来，一直报Unable to start service Intent { cmp= } U=0: not found  这个错，找不到服务，			intent.setClassName("com.test.tts",
"com.test.tts.TTsService");  包名和类名都是正常传的。

**Comment by xingjiyuan** [comment]
我的混淆配置
-dontwarn com.morgoo.**
-keep class com.morgoo.** { ;}
-keep class android.util.Singleton{;}
-keep class android.app.IServiceConnection{*;}

**Comment by chonrp27512** [comment]
@xingjiyuan 我试试看
