### ISSUE TITLE
报了 宿主不支持插件的abi环境，可能宿主运行时为64位，但插件只支持32位的错？

### ISSUE THREAD

**Issue by guobao90** [DroidPluginTeam/DroidPlugin#258]
宿主不支持插件的abi环境，可能宿主运行时为64位，但插件只支持32位。我直接跑项目里的TestPlugin.我在默认的apk路径下载了很多apk，都是报这个错，是什么原因啊？

**Comment by cxzadmini** [comment]
需要在宿主建一个libs目录放一个32位的空so就可以了

**Comment by triwater** [comment]
@cxzadmini 具体怎么做呢
