### ISSUE TITLE
插件中无法调起微信分享

### ISSUE THREAD

**Issue by smarxpan** [DroidPluginTeam/DroidPlugin#262]
插件中签名和包名都能拿到，而且也是对的。但是插件中无法调用微信分享，不能打开微信客户端。

**Comment by ouyangzn** [comment]
我这里分享没问题，但是调用QQ登录不行，QQ说登录功能版本旧，需要升级到最新版本，正常安装用QQ登录是没问题的

**Comment by HugoXX** [comment]
这个不是框架的问题。
微信分享/支付SDK把PackageName传递给微信App了，微信App会通过PackageName获取签名进行校验。
由于插件中的App没有实际的安装到OS，获取不到签名，校验不会通过就唤不起来。

解决方法：
在宿主提供分享能力接口，插件调用。
