### ISSUE TITLE
主程序 与插件程序之间可以调用方法吗？

### ISSUE THREAD

**Issue by agoodcoolman** [DroidPluginTeam/DroidPlugin#269]
主程序 是否实现公用的方法之后，在插件程序中调用，如果去实现？

或者是 插件与插件之间相互调用，把通用的代码放在一个插件中。

**Comment by agoodcoolman** [comment]
@cmzy 是不是可以用aidl方法去实现？

**Comment by dustookk** [comment]
宿主 提供个sdk给插件调用方法.    插件打包的时候不要把这个sdk打进包里.
就行了

**Comment by tiann** [comment]
不可以，需要用跨进程通信手段；比如AIDL。
