### ISSUE TITLE
一直卡在努力加载中 

### ISSUE THREAD

**Issue by Cornflower1991** [DroidPluginTeam/DroidPlugin#275]
0-12 18:09:17.085 29217-29217/com.host:PluginP06 E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
10-12 18:09:17.231 29217-29217/com.host:PluginP06 E/art: dlopen("/data/data/com.host/Plugin/com.tencent.mm/data/com.tencent.mm/app_recover_lib/libstlport_shared.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.host/Plugin/com.tencent.mm/data/com.tencent.mm/app_recover_lib/libstlport_shared.so" is 32-bit instead of 64-bit
10-12 18:09:17.319 29217-29217/com.host:PluginP06 E/art: dlopen("/data/data/com.host/Plugin/com.tencent.mm/data/com.tencent.mm/app_recover_lib/libstlport_shared.so", RTLD_LAZY) failed: dlopen failed: "/data/data/com.host/Plugin/com.tencent.mm/data/com.tencent.mm/app_recover_lib/libstlport_shared.so" is 32-bit instead of 64-bit
10-12 18:09:17.382 29217-29217/com.host:PluginP06 E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
10-12 18:09:17.582 29193-29193/com.host:PluginP02 E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
10-12 18:09:17.744 29322-29322/com.host:PluginP06 E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-36ms what=100 obj=ActivityRecord{377068e7 token=android.os.BinderProxy@247d3c94 {com.host/com.morgoo.droidplugin.stub.ActivityStub$P06$SingleTop00}} target=android.app.ActivityThread$H obj=ActivityRecord{377068e7 token=android.os.BinderProxy@247d3c94 {com.host/com.morgoo.droidplugin.stub.ActivityStub$P06$SingleTop00}} }
10-12 18:09:18.070 29322-29322/com.host:PluginP06 E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@39ebf41d,new=android.app.ActivityManagerProxy@39ebf41d
10-12 18:09:18.209 29322-29352/com.host:PluginP06 E/GED: Failed to get GED Log Buf, err(0)
10-12 18:09:18.854 29374-29374/com.host:PluginP02 E/PluginHelper: getMainLooper MessageQueue.IdleHandler:{ when=-28ms what=114 obj=CreateServiceData{token=android.os.BinderProxy@377068e7 className=com.morgoo.droidplugin.stub.ServiceStub$StubP02$P00 packageName=com.host intent=null} target=android.app.ActivityThread$H obj=CreateServiceData{token=android.os.BinderProxy@377068e7 className=com.morgoo.droidplugin.stub.ServiceStub$StubP02$P00 packageName=com.host intent=null} }
10-12 18:09:19.143 29374-29374/com.host:PluginP02 E/IActivityManagerHook: Install ActivityManager 3 Hook  old=android.app.ActivityManagerProxy@e9a94f4,new=android.app.ActivityManagerProxy@e9a94f4

**Comment by tytung** [comment]
Add jniLibs/armeabi-v7a/libPlugin.so to your host apk where libPlugin.so is 0 byte.

**Comment by zbcd20040112** [comment]
添加libdoem.so在armeabi-v7a目录中，可以为空且为任何名字
