### ISSUE TITLE
 DroidPlugin 是否支持宿主从 assets 里加载插件？

### ISSUE THREAD

**Issue by AlanCheen** [DroidPluginTeam/DroidPlugin#282]
DroidPlugin 是否支持宿主从 assets 里加载插件？还是说只支持加载 sdcard 的插件？

比如发布宿主 Apk 的时候，默认放一个插件在 assets 里。

**Comment by tiann** [comment]
手动copy出来就行了

**Comment by AlanCheen** [comment]
@tiann 好的 谢谢。
