### ISSUE TITLE
为什么我要把插件安装到手机上，才可以调用？

### ISSUE THREAD

**Issue by langxing** [DroidPluginTeam/DroidPlugin#286]
在我的手机上测试，只有把插件apk安装到手机上，才能调用插件里的apk。
      否则的话：
`               PackageManager pm = getPackageManager();
                Intent intent = pm.getLaunchIntentForPackage("com.plugin");
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(intent);`
       这里intent，会包空指针，谁能解释一下，难道是我使用的方式不对？

**Comment by Guolei1130** [comment]
我是下面这样，可以正常使用
```
int code = PluginManager.getInstance().installPackage(
                            new File("/sdcard/plugin.apk").getAbsolutePath()
                            , 0);

PackageManager pm = getPackageManager();
                Intent intent = pm.getLaunchIntentForPackage("com.example.pluginapk");
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(intent);
```

**Comment by langxing** [comment]
@Guolei130谢谢，我试试。

**Comment by langxing** [comment]
找到原因了，是我路径没有写完整，要把plugin.apk也写进去。

**Comment by MrHuJianQiang** [comment]
@langxing 路径写完整？是需要吧插件apk的绝对路劲写上去？

**Comment by langxing** [comment]
@MrHuJianQiang 是的额

**Comment by MrHuJianQiang** [comment]
@langxing 还是没太明白，能给我发个例子吗?绝对路径+包名？那是什么形式啊
