### ISSUE TITLE
nexus 5x 7.0系统 运行报错 

### ISSUE THREAD

**Issue by lcrjeff** [DroidPluginTeam/DroidPlugin#287]
大神，这个问题怎么解决
![image](https://cloud.githubusercontent.com/assets/2390203/20737750/bde643e4-b6e9-11e6-8c76-864f3a88cb3c.png)

**Comment by Mongolian** [comment]
补充一下：我也遇到了 nexus 5x 7.0 安装成功，启动失败，获取intent 是空的
PackageManager pm = getActivity().getPackageManager();
            Intent intent = pm.getLaunchIntentForPackage(item.packageInfo.packageName);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(intent);

**Comment by waitingal** [comment]
@Mongolian 我也遇到和你一样的问题 ，intent 是空的 ，请问你解决了吗？

**Comment by balizhuang2012** [comment]
我这里小米7.0也是启动失败，直接anr了

**Comment by a022012550** [comment]
我在华为mate 9上面也遇到了，直接anr

**Comment by cmzy** [comment]
fixed
