### ISSUE TITLE
android7.0报错

### ISSUE THREAD

**Issue by figobbq** [DroidPluginTeam/DroidPlugin#292]
# main
java.lang.StackOverflowError

1 java.util.HashMap.getEntry(HashMap.java:393)
2 java.util.HashMap.get(HashMap.java:348)
3 android.os.ServiceManager.getService(ServiceManager.java:51)
4 android.view.WindowManagerGlobal.getWindowManagerService(WindowManagerGlobal.java:187)
5 android.view.WindowManagerGlobal.getWindowManagerService(WindowManagerGlobal.java:189)
6 android.view.WindowManagerGlobal.getWindowManagerService(WindowManagerGlobal.java:189)

**Comment by SheepYoung** [comment]
目前测试机是华为 EMUI 7.0 系统，启动的进入initialize() 时候获取Windows manager的远程接口的时候，一直获取不到，
    public static IWindowManager getWindowManagerService() {
        synchronized (WindowManagerGlobal.class) {
            if (sWindowManagerService == null) {
                **sWindowManagerService = IWindowManager.Stub.asInterface(
                        ServiceManager.getService("window"));**
                try {
                    sWindowManagerService = getWindowManagerService();
                    ValueAnimator.setDurationScale(sWindowManagerService.getCurrentAnimatorScale());
                } catch (RemoteException e) {
                    throw e.rethrowFromSystemServer();
                }
            }
            return sWindowManagerService;
        }
    }

@cmzy

**Comment by SheepYoung** [comment]
刚才我有试过了其他的android 7.0 系统， nexus 6 和nexus  6p 同样遇到了这个问题

**Comment by qingyizeng** [comment]
DroidPlugin对android7.0系统一直没适配兼容好，都等了很久很久了。。。

**Comment by waitingal** [comment]
请问这个问题解决了吗？我也遇到同样的问题...

**Comment by h634462445** [comment]
我也遇到同样的问题...期待中

**Comment by h634462445** [comment]
我也遇到同样的问题...期待中

**Comment by wangyuetingtao** [comment]
也遇到类似的问题，很着急，期待大神早日解决

**Comment by cmzy** [comment]
fixed
