### ISSUE TITLE
Facebook SDK inside plugged app?

### ISSUE THREAD

**Issue by michealkazax** [DroidPluginTeam/DroidPlugin#295]
Hello, I'm trying to integrate facebook log-in sdk inside the plugged apps (Facebook sdk inside plugged app, I know I can just log in with the host then just put the token in the plugged apps, but I want to discuss for a better one). And what I've got was just an Exception:
_`Log in attempt failed: FacebookActivity could not be started. Please make sure you added FacebookActivity to the AndroidManifest.`_
This exception is not thrown through normal launch of plugged app itself (installed normaly) but it's thrown if things get launched by the host app.
After few tries against:
- Add facebook sdk to the host app
- Modified AndroidManifest.xml on the host app.
I still cant figure things out. 
Is there a way where I can make things work?

**Comment by cmzy** [comment]
Could you send  your plugged app to me?

**Comment by cmzy** [comment]
Could you send  your plugged app to me for test?

**Comment by michealkazax** [comment]
@cmzy  Thank you for reply. 
Here's the apk link:
https://www.dropbox.com/s/px97k8m7qrgk8w1/app-debug.apk?dl=0

**Comment by cmzy** [comment]
I think IntentMatcher has a bug.
the 
Intent { act=NATIVE_WITH_FALLBACK cmp=com.example.facebooksdkpluggedtest/com.facebook.FacebookActivity (has extras) }

can not match FacebookActivity, You can add action NATIVE_WITH_FALLBACK on your manifest.xml
