### ISSUE TITLE
为啥不支持含有so文件的插件？

### ISSUE THREAD

**Issue by dianhui** [DroidPluginTeam/DroidPlugin#298]
有计划支持么？

如果进行扩展，有坑吗？

**Comment by cmzy** [comment]
支持啊

**Comment by zlg2338781286** [comment]
同问，我们的插件使用了百度地图带有so文件，打开就崩溃，要怎么做呢

**Comment by cmzy** [comment]
需要native andhook

**Comment by zlg2338781286** [comment]
关于so文件的native hook在DroidPlugin框架中什么时候能开发出来

**Comment by cmzy** [comment]
https://github.com/DroidPluginTeam/NativeIORedirect

**Comment by jessehev** [comment]
【https://github.com/DroidPluginTeam/NativeIORedirect】 这个怎么用啊。。没有文档看不懂啊。
