### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by jarrahwu** [DroidPluginTeam/DroidPlugin#30]
Warning: com.morgoo.droidplugin.hook.proxy.IActivityManagerHook$1: can't find superclass or interface android.util.Singleton
Warning: com.morgoo.droidplugin.hook.proxy.IActivityManagerHook$1: can't find referenced class android.util.Singleton
Warning: com.morgoo.droidplugin.hook.proxy.IActivityManagerHook$1: can't find referenced class android.util.Singleton
Warning: com.morgoo.droidplugin.hook.proxy.IActivityManagerHook$1: can't find referenced class android.util.Singleton
Warning: there were 4 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)

**Comment by cmzy** [comment]
在混淆文件中加一个dontwarn就成了。

**Comment by jiezili** [comment]
-keep class android.util.Singleton {*;}

**Comment by cmzy** [comment]
@jiezili 说的对。close
