### ISSUE TITLE
Is DroidPlugin working in android-6(sdk version-25) applications?

### ISSUE THREAD

**Issue by TamilanPeriyasamy** [DroidPluginTeam/DroidPlugin#309]
I'm getting Errors in queryIntentServices android method

userId args are missing for the below override methods.
Example override methods: 
   PackageInfo getPackageInfo(String packageName, int flags);
   List<ResolveInfo> queryIntentServices(in Intent intent,String resolvedType, int flags);
   ResolveInfo resolveIntent(in Intent intent, String resolvedType, int flags);
   List<ResolveInfo> queryIntentActivities(in Intent intent, String resolvedType, int flags);
   List<ResolveInfo> queryIntentReceivers(in Intent intent,String resolvedType, int flags);
   ResolveInfo resolveService(in Intent intent,String resolvedType, int flags);
   List<ResolveInfo> queryIntentContentProviders(in Intent intent,String resolvedType, int flags);
   and extra .....

**Comment by cmzy** [comment]
Yes,it is work in android-6. but you have to do something to fix a few issues.
