### ISSUE TITLE
插件安装后目录结构为何与安装APK时不一致？

### ISSUE THREAD

**Issue by haimo-free** [DroidPluginTeam/DroidPlugin#310]
APK安装：/data/data/com.plugin.package/
插件安装：/data/data/com.host.package/Plugin/com.plugin.package/_**data**_/com.plugin.package/
插件安装时多了一层_**data**_目录会引起兼容问题，不是这么做是何原因？

**Comment by cmzy** [comment]
这个没特别的原因，你可以修改成任何目录都可以。但是要注意安全和兼容性

**Comment by jessehev** [comment]
如果把该目录改成sdcard的目录安装时就提示【宿主不支持插件的abi环境，可能宿主运行时为64位，但插件只支持32位的错】而且目录能成功创建但是目录里面是空的。这是怎么回事？

**Comment by jessehev** [comment]
难道 只能是/data/data/../目录吗？
