### ISSUE TITLE
ApiTest项目的NativeTestActivity没有注册到AndroidManifest.xml 注册后，运行报错

### ISSUE THREAD

**Issue by leafseelight** [DroidPluginTeam/DroidPlugin#334]
ApiTest项目的NativeTestActivity没有注册到AndroidManifest.xml
注册后，运行报错
> java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.leaf.plugin/Plugin/com.example.ApiTest/lib/libTest.so" is 32-bit instead of 64-bit

**Comment by cmzy** [comment]
只编译32位so即可。
