### ISSUE TITLE
Nexus 6 上，插件无法读取文件的问题

### ISSUE THREAD

**Issue by weijianfeng** [DroidPluginTeam/DroidPlugin#380]
android 7.1.2

插件中需要访问外部sd卡目录，localdirstr为路径，读取内容
通过 File rootFile = new File(localDirStr);
rootFile 下文件列表为空。实际有值。

插件单独安装的情况，读取没问题。

**Comment by weijianfeng** [comment]
我的锅。。。

**Comment by TIIEHenry** [comment]
解决了？

**Comment by weijianfeng** [comment]
解决了，6.0以上，如果插件需要一些运行时权限，宿主中要记得申请。
