### ISSUE TITLE
android8.0 有服务的插件启动异常

### ISSUE THREAD

**Issue by yeyutianya** [DroidPluginTeam/DroidPlugin#399]
09-14 09:23:45.685 5181-5194/com.xxx:PluginP07 E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                           java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
                                                                               at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:60)
                                                                               at android.os.Binder.execTransact(Binder.java:674)
09-14 09:23:45.685 5181-5194/com.xxx:PluginP07 E/JavaBinder: java.lang.Error thrown during binder transaction (stack trace follows) : 
09-14 09:23:45.685 5181-5194/com.xxx:PluginP07 W/System.err: java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
09-14 09:23:45.685 5181-5194/com.xxx:PluginP07 W/System.err:     at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:60)
09-14 09:23:45.685 5181-5194/com.huawei.genexcloud:PluginP07 W/System.err:     at android.os.Binder.execTransact(Binder.java:674)
09-14 09:23:45.686 5181-5194/com.xxx:PluginP07 A/zygote64: jni_internal.cc:508] JNI FatalError called: java.lang.Error thrown during binder transaction: java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
09-14 09:23:45.689 5181-5195/com.xxx:PluginP07 E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                           java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
                                                                               at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:60)
                                                                               at android.os.Binder.execTransact(Binder.java:674)
09-14 09:23:45.690 5181-5195/com.xxx:PluginP07 E/JavaBinder: java.lang.Error thrown during binder transaction (stack trace follows) : 
09-14 09:23:45.690 5181-5195/com.xxx:PluginP07 W/System.err: java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
09-14 09:23:45.690 5181-5195/com.xxx:PluginP07 W/System.err:     at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:60)
09-14 09:23:45.690 5181-5195/com.xxx:PluginP07 W/System.err:     at android.os.Binder.execTransact(Binder.java:674)
09-14 09:23:45.690 5181-5195/com.xxx:PluginP07 A/zygote64: jni_internal.cc:508] JNI FatalError called: java.lang.Error thrown during binder transaction: java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"

**Comment by yeyutianya** [comment]
需要在IActivityManagerHookHandle类中的bindService方法添加
  public void connected(ComponentName name, IBinder service, boolean dead) {
                        try {
                            MethodUtils.invokeMethod(oldIServiceConnection, "connected", new ComponentName(mInfo.packageName, mInfo.name), service, dead);
                        } catch (Exception e) {
                            Log.e(TAG, "invokeMethod connected", e);
                        }
                    }

**Comment by zqyu2** [comment]
Hi @yeyutianya， 请问添加这段代码就可以了吗   别的地方需要改动吗？
