### ISSUE TITLE
插件Activity最大深度是3

### ISSUE THREAD

**Issue by SheepYoung** [DroidPluginTeam/DroidPlugin#415]
如题, 插件的Activity 最大深度是3, 能否配置, 增加activity 深度?  

举个栗子:  HostActiviy -> **PluginActivityA**->PuginActivityB->PluginActivityC->PluginActivityD;
然后我按back返回 :  PLuginActivityC->PuginActivityB->**HostActivity**
PluginActivityA 被回收了, 这个能否配置? 感觉只有3个不太够用

**Comment by SheepYoung** [comment]
我跟了一下代码, 将PluginManager.STUB_NO_ACTIVITY_MAX_NUM 的值改大一定应该问题不大吧, 比如说改成10  @cmzy

**Comment by nanxiao198908** [comment]
之前修改插件包activity的启动模式个数解决了这个问题
